#!/usr/bin/env python
import time
import threading
import rospy
import tf
import geometry_msgs.msg

def motion(message):
    pass

def main():
    motion_sub = rospy.Subscriber("/planif", Planification, motion)

# vim: ft=python et sw=4 sts=4
