#!/usr/bin/env python
import os
import sys
import rospy
this_dir = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(0, os.path.join(this_dir, 'src'))
from slam import main

rospy.init_node('slam_strategy')
main()
rospy.spin()

# vim: ft=python et sw=4 sts=4
